"""
Demo / seed data for when external APIs are unavailable.
These are real, well-known primitive camping areas across the US.
"""

DEMO_CAMPSITES = [
    {
        "id": 1001,
        "name": "Hazel Creek Backcountry Campsite",
        "lat": 35.5351,
        "lon": -83.6513,
        "distance_mi": 8.4,
        "score": 12,
        "flags": ["backcountry", "free", "no reservation", "public land"],
        "tags": {"backcountry": "yes", "fee": "no", "operator": "national park service", "tourism": "camp_site"},
        "website": "https://www.nps.gov/grsm/planyourvisit/backcountry-camping.htm",
        "description": "Remote backcountry site on Hazel Creek in GSMNP. No facilities, fire rings only.",
    },
    {
        "id": 1002,
        "name": "Lost Horse Creek Dispersed Camp",
        "lat": 45.6833,
        "lon": -113.6667,
        "distance_mi": 14.2,
        "score": 11,
        "flags": ["backcountry", "free", "informal", "public land"],
        "tags": {"backcountry": "yes", "fee": "no", "operator": "usfs", "informal": "yes", "tourism": "camp_site"},
        "website": "",
        "description": "BLM dispersed camping along Lost Horse Creek, Bitterroot NF. Pack-it-in, pack-it-out.",
    },
    {
        "id": 1003,
        "name": "Coyote Gulch Primitive Camp",
        "lat": 37.5201,
        "lon": -111.4266,
        "distance_mi": 22.1,
        "score": 10,
        "flags": ["backcountry", "free", "no reservation", "public land"],
        "tags": {"backcountry": "yes", "fee": "no", "operator": "blm", "tourism": "camp_site"},
        "website": "https://www.blm.gov/visit/coyote-gulch",
        "description": "Wild slot canyon camping in Grand Staircase-Escalante. Self-issued permit in trailhead register.",
    },
    {
        "id": 1004,
        "name": "Dolly Sods Backcountry Area",
        "lat": 39.0053,
        "lon": -79.3942,
        "distance_mi": 31.5,
        "score": 10,
        "flags": ["backcountry", "free", "no reservation"],
        "tags": {"backcountry": "yes", "fee": "no", "operator": "usfs", "reservation": "no", "tourism": "camp_site"},
        "website": "https://www.fs.usda.gov/recarea/mnf/recarea/?recid=6905",
        "description": "High-altitude heath barrens in Monongahela NF, WV. Dispersed camping everywhere, no trail required.",
    },
    {
        "id": 1005,
        "name": "Superstition Wilderness Camp",
        "lat": 33.4734,
        "lon": -111.3782,
        "distance_mi": 18.7,
        "score": 9,
        "flags": ["backcountry", "free", "public land"],
        "tags": {"backcountry": "yes", "fee": "no", "operator": "usfs", "toilets": "no", "tourism": "camp_site"},
        "website": "https://www.fs.usda.gov/tonto",
        "description": "Tonto NF Superstition Wilderness. 300 ft setback from water required. No campfires in summer.",
    },
    {
        "id": 1006,
        "name": "Paria Canyon Primitive Site",
        "lat": 36.8670,
        "lon": -111.9002,
        "distance_mi": 45.3,
        "score": 9,
        "flags": ["backcountry", "no reservation"],
        "tags": {"backcountry": "yes", "operator": "blm", "tourism": "camp_site"},
        "website": "https://www.blm.gov/visit/paria-canyon",
        "description": "Sand camping in Paria Canyon, UT. Flash flood awareness essential. Day use/overnight permit required.",
    },
    {
        "id": 1007,
        "name": "Shawnee Hills Informal Camp",
        "lat": 37.5153,
        "lon": -88.7062,
        "distance_mi": 12.9,
        "score": 7,
        "flags": ["free", "informal", "public land"],
        "tags": {"fee": "no", "informal": "yes", "operator": "state forest", "tourism": "camp_site"},
        "website": "",
        "description": "Dispersed camping in Shawnee National Forest, IL. No permit needed. Primitive pull-offs along forest roads.",
    },
    {
        "id": 1008,
        "name": "Lake Ouachita Shoreline Camp",
        "lat": 34.5615,
        "lon": -93.3099,
        "distance_mi": 9.8,
        "score": 6,
        "flags": ["free", "no reservation"],
        "tags": {"fee": "no", "reservation": "no", "operator": "usfs", "tourism": "camp_site"},
        "website": "https://www.fs.usda.gov/ouachita",
        "description": "Shoreline primitive camping on Lake Ouachita in Ouachita NF, AR. Boat-in or hike-in only.",
    },
    {
        "id": 1009,
        "name": "Allegheny Wilderness Hut",
        "lat": 41.7326,
        "lon": -79.0145,
        "distance_mi": 27.4,
        "score": 8,
        "flags": ["backcountry", "wilderness hut", "free"],
        "tags": {"tourism": "wilderness_hut", "fee": "no", "operator": "usfs"},
        "website": "",
        "description": "Adirondack lean-to shelter in Allegheny NF. First-come first-served, 3-night max stay.",
    },
    {
        "id": 1010,
        "name": "Gila Wilderness Dispersed",
        "lat": 33.2312,
        "lon": -108.2659,
        "distance_mi": 38.6,
        "score": 11,
        "flags": ["backcountry", "free", "no reservation", "public land"],
        "tags": {"backcountry": "yes", "fee": "no", "operator": "usfs", "reservation": "no", "tourism": "camp_site"},
        "website": "https://www.fs.usda.gov/detail/gila/",
        "description": "America's first wilderness area. Camp anywhere 300 ft from trails/water. No permit required.",
    },
]

DEMO_REDDIT_POSTS = {
    "default": [
        {
            "id": "abc123",
            "title": "Weekend at Dolly Sods — honest review",
            "url": "https://www.reddit.com/r/CampingandHiking/comments/abc123",
            "score": 847,
            "num_comments": 62,
            "subreddit": "CampingandHiking",
            "snippet": "Just got back from 3 nights in Dolly Sods Wilderness. Incredible high-altitude heath barrens, super windy even in August — bring a 4-season or at least a strong 3-season tent. Water from streams is abundant but filter everything. Bear activity was low. The views from Rohrbaugh Plains are worth every mile.",
            "created_utc": 1716000000,
        },
        {
            "id": "def456",
            "title": "Tips for primitive camping in Gila Wilderness — first timer",
            "url": "https://www.reddit.com/r/backpacking/comments/def456",
            "score": 512,
            "num_comments": 34,
            "subreddit": "backpacking",
            "snippet": "Just finished a 5-day loop in the Gila. No permit needed which is awesome. The river crossings are constant but manageable in late summer — maybe 60 knee-deep crossings on the Middle Fork trail alone. Hot springs at the end were the reward. Highly recommend.",
            "created_utc": 1714000000,
        },
        {
            "id": "ghi789",
            "title": "BLM dispersed camping guide: find free primitive sites on public land",
            "url": "https://www.reddit.com/r/camping/comments/ghi789",
            "score": 3241,
            "num_comments": 189,
            "subreddit": "camping",
            "snippet": "Use the BLM's website and the onX Backcountry app to find land ownership layers. Green = BLM, generally open to free dispersed camping with a 14-day stay limit. Stay 300 ft from water, pack out all trash. Most forest roads on national forest land are also fair game.",
            "created_utc": 1710000000,
        },
        {
            "id": "jkl012",
            "title": "Coyote Gulch — best slot canyon camping in Utah?",
            "url": "https://www.reddit.com/r/wildernesscamping/comments/jkl012",
            "score": 1102,
            "num_comments": 77,
            "subreddit": "wildernesscamping",
            "snippet": "Did Coyote Gulch last October, camped at Red Well. You sign in at the trailhead register (no permit fee). The canyon itself is otherworldly — natural bridges, arches, waterfalls. In shoulder season it's not crowded. Water from Coyote Creek needs filtering.",
            "created_utc": 1698000000,
        },
        {
            "id": "mno345",
            "title": "Shawnee National Forest hidden gems for dispersed camping",
            "url": "https://www.reddit.com/r/camping/comments/mno345",
            "score": 423,
            "num_comments": 28,
            "subreddit": "camping",
            "snippet": "Shawnee is massively underrated. Garden of the Gods, Bell Smith Springs, Lusk Creek Wilderness all allow primitive camping for free. No toilet, no water, just you and the sandstone bluffs. Drive the forest roads in a high-clearance vehicle and you'll find spots nobody uses.",
            "created_utc": 1712000000,
        },
        {
            "id": "pqr678",
            "title": "Hazel Creek GSMNP — worth the effort?",
            "url": "https://www.reddit.com/r/backpacking/comments/pqr678",
            "score": 674,
            "num_comments": 45,
            "subreddit": "backpacking",
            "snippet": "Only accessible by boat across Fontana Lake or a brutal 26-mile round trip. But that's why it's magic — complete solitude, huge old-growth hemlocks (the few still alive), wild trout, total silence. Get the backcountry permit through the NPS website. Sites fill fast in fall.",
            "created_utc": 1715000000,
        },
    ]
}
